substitutions:
  name: esphome-web-ketchen
  friendly_name: 8266-kitchen

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: "home"       # Replace with your Wi-Fi SSID
  password: "home2014"  # Replace with your Wi-Fi password

  # Optional: Enable fallback hotspot in case Wi-Fi connection fails
  ap:
    ssid: "ESPHomeKitchen"
    password: "home2014"  # Replace with a fallback password


# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

text_sensor:
  - platform: version
    name: Date
  - platform: wifi_info
    ip_address:
      name: $friendly_name ip
    ssid:
      name: $friendly_name ssid
      
    
sensor:
  - platform: dht
    pin: 13
    temperature:
      name: "Test DHT Temperature"
    humidity:
      name: "Test DHT Humidity"
    update_interval: 60s
    
# Uptime sensor
  - platform: uptime
    name: $friendly_name uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    id: wifi_signal_db
    name: RSSI
    entity_category: "diagnostic"
    update_interval: 60s
  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    
    
binary_sensor:
  - platform: gpio
    pin: 
      number: 14  
      mode: INPUT_PULLUP
      inverted: false
    name: "Door Sensor"
    device_class: door
    
  - platform: gpio
    pin: 
      number: 5  
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    device_class: light
    filters:
        - delayed_on: 10ms
    on_press:
        - switch.toggle: led_button
    
  - platform: gpio
    pin: 
      number: 12  
      mode: INPUT
    name: "PIR Sensor"
    device_class: motion
    filters:
      - delayed_on: 10ms  # Debounce the signal
      - delayed_off: 2s   # Keep the sensor on for 5 seconds after motion is detected
      
switch:
  - platform: gpio
    name: "Led Button"
    pin: 4
    id: led_button

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:
