esphome:
  name: ip-cam
  friendly_name: ip-cam

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3WsH7cLxkr8JcJUFvqkSfJwvDs9r2zerPgSJQ8hf1KA="

ota:
  - platform: esphome

wifi:
  ssid: "home"
  password: "home2014"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ip-Cam Fallback Hotspot"
    password: "home2014"

captive_portal:
    
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  name: My Camera

# http server setting
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot